# Generated by Django 5.2.4 on 2025-07-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_mission_missionitem_missionstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionItem',
        ),
        migrations.AddField(
            model_name='mission',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missionstatus',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
